apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: capsule-system
spec:
  interval: 10m
  chart:
    spec:
      chart: capsule
      version: 0.7.4
      sourceRef:
        kind: HelmRepository
        name: capsule
        namespace: capsule-system
  values:
    replicaCount: 2
    manager:
      manager:
      protectedNamespaceRegex: "^kube-.*|.*-system$|^flux$|^capabilities$|^cert-manager$|^teleport-kube-agent$|^ingress-controllers$"
