apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: capsule-proxy
  namespace: capsule-system
spec:
  interval: 1h0m0s
  url: https://projectcapsule.github.io/charts/
  timeout: 60s