apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-controllers
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-controllers
  values:
    controller:
      allowSnippetAnnotations: true
      config:
        annotations-risk-level: "Critical"
