apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: teleport-kube-agent
  namespace: teleport-kube-agent
spec:
  interval: 30s
  url: https://github.com/kubelize/kube-clusters
  ref:
    branch: main