apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - ../../apps/operators/storage/csi-proxmox/
  - ../../apps/addons/storageclasses/proxmox-csi/

  - config/

patches:
  - target:
      kind: StorageClass
      name: proxmox
    path: patches/csi-proxmox/zfs-device.yaml