apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - ../../apps/bundles/mizu-r1/

  - config/

patches:
  - target:
      kind: StorageClass
      name: proxmox
    path: patches/csi-proxmox/zfs-device.yaml
  - target:
      kind: HealmRelease
      name: teleport-kube-agent
      path: patches/teleport-kube-agent/patch.yaml